version: '3'
services:
  node-app:
    build:
      context: . 
    ports:
      - "3000:3000"
    volumes:
      - .:/app    
    env_file:
      - .env     
    command: sh -c "npm install && npm start"
